apiVersion: v1
kind: Service
metadata:
  name: {{ include "webtens.fullname" . }}
  labels:
    {{- include "webtens.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "webtens.fullname" . }}
  ports:
    - name: http
      port: 8000
      targetPort: webtens-port

  type: NodePort
