import Vue from "vue";
import IntensButton from "./IntensButton.vue";
import IntensButtonBar from "./IntensButtonBar.vue";
import IntensContainer from "./IntensContainer.vue";
import IntensContextmenu from "./IntensContextmenu.vue";
import IntensContextmenuItem from "./IntensContextmenuItem.vue";
import IntensCycleButton from "./IntensCycleButton.vue";
import IntensDiagram from "./IntensDiagram/IntensDiagram.vue";
import IntensFieldgroup from "./IntensFieldgroup.vue";
import IntensFolder from "./IntensFolder.vue";
import IntensHeader from "./IntensHeader.vue";
import IntensIconView from "./IntensIconView.vue";
import IntensIndex from "./IntensIndex.vue";
import IntensIndexMenu from "./IntensIndexMenu.vue";
import IntensInput from "./IntensInput.vue";
import IntensSlider from "./IntensSlider.vue";
import IntensLabel from "./IntensLabel.vue";
import IntensList from "./IntensList.vue";
import IntensMenubar from "./IntensMenubar.vue";
import IntensMenubarButton from "./IntensMenubarButton.vue";
import IntensMessageline from "./IntensMessageline.vue";
import IntensMessage from "./IntensMessage.vue";
import IntensNavigator from "./IntensNavigator.vue";
import IntensNavigatorNode from "./IntensNavigatorNode.vue";
import IntensPlot2D from "./IntensPlot2D.vue";
import IntensPlot3D from "./IntensPlot3D.vue";
import IntensPixmap from "./IntensPixmap.vue";
import IntensRadio from "./IntensRadio.vue";
import IntensScrolledText from "./IntensScrolledText.vue";
import IntensSelect from "./IntensSelect.vue";
import IntensSeparator from "./IntensSeparator.vue";
import IntensStretch from "./IntensStretch.vue";
import IntensTable from "./IntensTable.vue";
import IntensText from "./IntensText.vue";
import IntensToggle from "./IntensToggle.vue";
import IntensThermo from "./IntensThermo.vue";
import IntensVoid from "./IntensVoid.vue";

const prefix = "intens";

Vue.component(`${prefix}-Button`, IntensButton);
Vue.component(`${prefix}-Buttonbar`, IntensButtonBar);
Vue.component(`${prefix}-Container`, IntensContainer);
Vue.component(`${prefix}-context-menu`, IntensContextmenu);
Vue.component(`${prefix}-context-menu-item`, IntensContextmenuItem);
Vue.component(`${prefix}-Cycle_Button`, IntensCycleButton);
Vue.component(`${prefix}-Diagram`, IntensDiagram);
Vue.component(`${prefix}-FieldGroup`, IntensFieldgroup);
Vue.component(`${prefix}-Folder`, IntensFolder);
Vue.component(`${prefix}-Header`, IntensHeader);
Vue.component(`${prefix}-IconView`, IntensIconView);
Vue.component(`${prefix}-Index`, IntensIndex);
Vue.component(`${prefix}-IndexMenu`, IntensIndexMenu);
Vue.component(`${prefix}-Textfield`, IntensInput);
Vue.component(`${prefix}-Slider`, IntensSlider);
Vue.component(`${prefix}-Label`, IntensLabel);
Vue.component(`${prefix}-List`, IntensList);
Vue.component(`${prefix}-Menubar`, IntensMenubar);
Vue.component(`${prefix}-MenuButton`, IntensMenubarButton);
Vue.component(`${prefix}-Messagebar`, IntensMessageline);
Vue.component(`${prefix}-Message`, IntensMessage);
Vue.component(`${prefix}-Navigator`, IntensNavigator);
Vue.component(`${prefix}-NavigatorNode`, IntensNavigatorNode);
Vue.component(`${prefix}-Pixmap`, IntensPixmap);
Vue.component(`${prefix}-Plot2D`, IntensPlot2D);
Vue.component(`${prefix}-Plot3D`, IntensPlot3D);
Vue.component(`${prefix}-ScrolledText`, IntensScrolledText);
Vue.component(`${prefix}-Radio`, IntensRadio);
Vue.component(`${prefix}-ComboBox`, IntensSelect);
Vue.component(`${prefix}-Separator`, IntensSeparator);
Vue.component(`${prefix}-Stretch`, IntensStretch);
Vue.component(`${prefix}-Table`, IntensTable);
Vue.component(`${prefix}-Text`, IntensText);
Vue.component(`${prefix}-Toggle`, IntensToggle);
Vue.component(`${prefix}-Thermo`, IntensThermo);
Vue.component(`${prefix}-Void`, IntensVoid);

Vue.component("intens-Dialog_Button", IntensButton);
